### ISSUE TITLE
exception if unknows/wrong token is in receiver token error

### ISSUE THREAD

**Issue by trx222** [eladnava/fcm-v1-http2#4]
Hi,

thanks for your work on this lib.

I have a large number of receivers and tested your demo code. If I have a token that is not known by firebase you send function gives an exception and goes to catch function. This should not happen, because you can not identify valid token and if they have received the notification between unvalid tokens.

To test just use your demo code an add some strings to receiver token array:

const tokens = [
  'fF9t16fhQiqp5i-...valid-token',
  'device-token-1-unvalid'
  'device-token-2-unvalid'
];

An exception occures:

Sending failed: {
  code: 400,
  message: 'The registration token is not a valid FCM registration token',
  status: 'INVALID_ARGUMENT',
  details: [
    {
      '@type': 'type.googleapis.com/google.firebase.fcm.v1.FcmError',
      errorCode: 'INVALID_ARGUMENT'
    }
  ]
}

can you fix this and give back the invalid tokens also in then resolve?

best

**Comment by eladnava** [comment]
Hi @trx222,
Thanks for reporting this issue. I'd be glad to assist.

This has now been resolved in commit [aa44914](https://github.com/eladnava/fcm-v1-http2/commit/aa44914922de0ef9297283d4a2e9a2a6b28fa542) and published to `npm` in version `1.0.3` of the package.

Please update to the latest version by running this command:

```
npm install fcm-v1-http2@latest --save
```

Then, try to reproduce the issue and let me know if it is indeed resolved.

**Comment by trx222** [comment]
great, works like expected!

Thank you very much.
