### ISSUE TITLE
Token marked as unregistered when message payload is invalid (but token is still valid)

### ISSUE THREAD

**Issue by marc0s** [eladnava/fcm-v1-http2#5]
As I understand, this code is in place to not throw an error but just inform of invalid **tokens**:

```
      if (response.error) {
        // App uninstall or invalid token?
        if (
          (response.error.details &&
            response.error.details[0].errorCode === "UNREGISTERED") ||
          (response.error.code === 400 &&
            response.error.status === "INVALID_ARGUMENT")
        ) 
```

I've just seen that if I send an invalid payload for a message (ie: `{key: 'unknown'}` as message) the library goes through that `if` branch and reports the token as `client.unregisteredTokens`. This is because the FCM response for such an invalid payload is as follows: 

```
{
  error: {
    code: 400,
    message: `Invalid JSON payload received. Unknown name "key" at 'message': Cannot find field.`,
    status: 'INVALID_ARGUMENT',
    details: [
      {
        '@type': 'type.googleapis.com/google.rpc.BadRequest',
        fieldViolations: [
          {
            field: 'message',
            description: `Invalid JSON payload received. Unknown name "key" at 'message': Cannot find field.`
          }
        ]
      }
    ]
  }
}
```

And that matches the `if` conditions. I think that this library should check on `details['@type']` as well (or instead) to make sure which kind of error FCM reported back.

**Comment by eladnava** [comment]
Hi @marc0s,
Thanks so much for reaching out and reporting this issue! I'd be glad to assist.

This has now been fixed in commit 51aadb3 and published to `npm` in version `1.0.4`. 

Please let me know if there's anything else I can help with.

**Comment by marc0s** [comment]
LGTM.

I'd probably have checked against `details[0]["@type"]`, because it feels more stable in time to me, though. 
It's working nonetheless.

Thanks!

**Comment by eladnava** [comment]
Hi @marc0s,
Thanks for your suggestion! Unfortunately the `details[0]["@type"]` returned when the provided FCM device token is invalid is quite ambiguous:

```
{
  code: 400,
  message: 'The registration token is not a valid FCM registration token',
  status: 'INVALID_ARGUMENT',
  details: [
    {
      '@type': 'type.googleapis.com/google.firebase.fcm.v1.FcmError',
      errorCode: 'INVALID_ARGUMENT'
    }
  ]
}
```

Since `type.googleapis.com/google.firebase.fcm.v1.FcmError` may also be returned in other cases, it is not specific enough to be used to detect an invalid FCM device token.

You're very welcome!
